### ISSUE TITLE
LIT crashing or not scaling if we have more number of classes i,e greater thant 500 classes ,multi-class

### ISSUE THREAD

**Issue by tiru1930** [PAIR-code/lit#416]

**Comment by iftenney** [comment]
This is a known issue, and we're hoping to have better support for a large number of classes in an upcoming release though there isn't a firm timeline yet.

Could you describe a bit more about your use case and the particular crash you're experiencing, so we can make sure it's covered or see if there's an interim fix?

**Comment by iftenney** [comment]
This should work better now as of v0.4; see https://pair-code.github.io/lit/demos/images.html for a demo with 1000 classes.

**Comment by bafonso** [comment]
Not sure this is related to lots of classes problems, but I am trying to use LIT on a dataset with 20 classes, ~5k examples and it while saving to cache my memory hit over 50GB of usage.. Is this expected? Could we optimize this somehow? I'd be happy to look into the code

**Comment by iftenney** [comment]
That's surprising - I would not expect such high usage from the # of classes; it should only be storing a vector of 20 floats for each example. Is your model returning per-token gradients, embeddings, or attention weights? These can be much much larger and could be responsible for a lot of the memory usage.

(Another possibility: if the preds are slices from a larger NumPy array, there can be memory issues as NumPy keeps a pointer around to the original array even if nothing else needs that anymore. See here for more: https://github.com/PAIR-code/lit/blob/main/lit_nlp/api/model.py#L51 - the fix is to do an explicit copy of the array before returning it from your model.)
